- docs/QUICK-START.md
The old one didn't work. I just copied the URL from https://github.com/hotwired/turbo-ios/blob/main/Docs/QuickStartGuide.md
> Fix start location [docs]

- .github/workflows/test.yml
- turbo/build.gradle
- turbo/src/main/AndroidManifest.xml
- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepository.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboFileUploadDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragmentCallback.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/http/TurboHttpRepository.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSessionCallback.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboDispatcherProvider.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboExtensions.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboFileProvider.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboUriAttributes.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboUriHelper.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboWebChromeClient.kt
- turbo/src/main/res/xml/file_provider_paths.xml
- turbo/src/test/kotlin/dev/hotwire/turbo/BaseRepositoryTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/delegates/TurboFileUploadDelegateTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/session/TurboSessionTest.kt
Allows file uploads from an `<input type=file>` element. The default `TurboWebChromeClient` behavior can be overridden by an app.
> Out-of-the-box support for file uploads

- docs/QUICK-START.md
I copied this from point 5 at https://github.com/hotwired/turbo-ios/blob/main/Docs/QuickStartGuide.md, then expanded a bit based on other Android gotchas I came across.
> Add note about non-HTTPS sites

- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboSwipeRefreshLayout.kt
This prevents the ViewGroup's dispatched hover events from trying to determine a custom order of its children when the WebView is being removed (there's no custom order anyway).
> Fix crash while using a stylus to navigate within the WebView

- turbo/src/main/assets/json/test-configuration.json
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavException.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepositoryTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/nav/TurboNavRuleTest.kt
This is not a supported situation. Modals should always have an underlying default context destination.
Addresses https://github.com/hotwired/turbo-android/issues/134
> Prevent replacing the root destination with a modal destination

- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt
To refresh a destination's contents, simply call `refresh()`:
```kotlin
class WebFragment : TurboWebFragment() {
// ...
private fun respondToNativeFeature() {
// Refresh the WebView contents
refresh()
// Or, refresh the contents without displaying progress
refresh(displayProgress = false)
}
}
```
To refresh the current destination from your Activity, use the `delegate`:
```kotlin
class MainActivity : AppCompatActivity(), TurboActivity {
// ...
private fun refreshAfterResumingApp() {
delegate.currentNavDestination?.refresh()
}
}
```
Addresses https://github.com/hotwired/turbo-android/issues/137
> Allow a destination's contents to be refreshed

- docs/NAVIGATION.md
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboActivityDelegate.kt
Small updates to https://github.com/hotwired/turbo-android/pull/138
- Adds a `refresh` method on the `TurboActivityDelegate` so that you can call `delegate.refresh()` just like all other navigation methods.
- Adds `refresh` to the docs - https://github.com/hotwired/turbo-android/blob/main/docs/NAVIGATION.md
> `refresh()` tweaks and docs

- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboWebChromeClient.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboWebView.kt
Addresses https://github.com/hotwired/turbo-android/issues/144
Some `target="_blank"` links may not always propose visits (such as when embedded in `<iframe>` content), unless `webView.settings.setSupportMultipleWindows(true)` is enabled and `WebChromeClient.onCreateWindow()` is handled.
> Allow all target="_blank" links to propose visits

- turbo/src/main/kotlin/dev/hotwire/turbo/activities/TurboActivityObserver.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboActivityDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/observers/TurboActivityObserver.kt
Addresses #148 
`WebView` maintains its own internal timing to flush in-memory cookies to persistent storage. This means cookies may not have been persisted before leaving the app. Ensure that cookies are always flushed when the `TurboActivity` stops.
> Ensure that WebView cookies are always persisted across app restarts

- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/imageviewer/ImageViewerFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebModalFragment.kt
- turbo/build.gradle
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragment.kt
AndroidX has deprecated `Fragment.onActivityCreated()`, so prevent its further use in the library and consuming apps.
> Remove onActivityCreated() use from all library fragments

- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboFileChooserDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt
AndroidX has deprecated `Fragment.onActivityResult()`, so prevent its further use in the library and consuming apps.
> Remove onActivityResult() use from all library Fragments

- turbo/src/test/kotlin/dev/hotwire/turbo/nav/TurboNavRuleTest.kt
`http://hotwire.dev/` → `https://hotwired.dev/`
As per: https://github.com/hotwired/hotwire-site/commit/22a11ace88459e98a8dd2d5dd7efd5176b4baabe
> Update the Hotwire domain

- docs/QUICK-START.md
Fix the type of `TurboSessionNavHostFragment#registeredActivities`
> Fix QUICK-START.md for 7.0.0-beta11

- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt
Currently Turbo Native will attempt to navigate to any link, even if it's not a valid URL. This can cause the app to crash ([here](https://github.com/hotwired/turbo-android/blob/main/turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfiguration.kt#L93)) if you click on a link like `sms:+55555555?body=hi`, since `URL(location)` doesn't recognise `sms:` links as valid.
To properly handle this you should implement [this code](https://github.com/hotwired/turbo-android/blob/main/demo/src/main/kotlin/dev/hotwire/turbo/demo/base/NavDestination.kt#L18..L57). But if you forget to, or if someone working on the web app ships a new link without you knowing about it, you don't want this to cause a scenario where clicking a link can crash the native app.
This PR avoids that, by not navigating …
> Don't attempt to navigate to invalid URLs

- turbo/src/main/assets/json/test-configuration.json
- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfiguration.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavQueryStringPresentation.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepositoryTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/nav/TurboNavRuleTest.kt
Addresses: https://github.com/hotwired/turbo-android/issues/157
The (new) default behavior will no longer ignore query strings to evaluate if locations are the same. To use the previous behavior, use the new `query_string_presentation` path configuration option:
```json
{
"patterns": [
"/feature"
],
"properties": {
"query_string_presentation": "replace"
}
}
```
> New path properties presentation option for same-path visits with query strings

- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
Addresses the issue outlined in #161.
> Ignore the web fragment `refresh()` if the WebView doesn't have a url loaded yet

- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/session/TurboSessionTest.kt
The WebView is always detached from the current Fragment destination before visiting a new Fragment destination. 
Consider the following flow:
1. Destination `A` is the current web destination
2. Start visit to destination `B` (WebView is detached from `A`)
3. Destination `B` is current destination and is all native (no WebView)
4. Go back to destination `A` in the backstack
5. WebView is reattached to destination `A`. The WebView visit is still displaying `A`'s visit location. We no longer perform a Turbo `restore` visit to `A`'s location, since this would be considered a same-page visit. Instead, synthetically call `visitRendered()` and `visitCompleted()`, since the WebView is already displaying the correct location contents.
> Synthetically restore the session's current visit if the WebView's visit hasn't changed

- demo/src/main/kotlin/dev/hotwire/turbo/demo/base/NavDestination.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebBottomSheetFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebFragment.kt
- demo/src/main/res/layout/toolbar_progress.xml
- demo/src/main/res/menu/web.xml
- demo/src/main/res/values/strings.xml
- turbo/src/main/assets/js/turbo_bridge.js
- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepository.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragmentCallback.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/observers/TurboWindowThemeObserver.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSessionCallback.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/session/TurboSessionTest.kt
This implements the form submission adapter APIs and allows apps to hook into those callbacks to display form submission progress in their UI.
The demo app has been updated to display a progress indicator in the top right of the toolbar during form submission events:
> Implement the form submission adapter APIs 

- turbo/src/main/assets/js/turbo_bridge.js
This ensures we get the proper visit callbacks and the page content is not stale when performing a visit to an anchor path for the same URL that's already loaded in the shared WebView.
> Skip the same-page anchor scrolling behavior for visits initiated from the native side

- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
We are trying to debug an issue where `visitProposedToLocation` isn't reliably getting called by `shouldOverrideUrlLoading`. This logging will help debug that.
> Log what `shouldProposeThrottledVisit` returns

- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
Fixes https://github.com/hotwired/turbo-android/issues/217
The 500ms delay logic in `shouldOverrideUrlLoading` / `shouldProposeThrottledVisit` is fine for link clicks, but doesn't make sense when following multiple redirects. So this PR just skips that logic while in a cold boot redirect.
See https://github.com/hotwired/turbo-android/issues/217 for more detail on example scenarios and how to replicate. There's another branch ([here](https://github.com/hotwired/turbo-android/compare/main...ghiculescu:slow-redirect)) that you can use to replicate, but I figured I'd keep the fix PR small and if you'd like the extra examples added to the demo I can make followup PRs for that.
> Fix app breaking on cold boot redirects

- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSessionNavHostFragment.kt
This works around a bug seen in the Basecamp app where resetting the `NavHostFragment` and then recreating the `Activity` to update its `Theme` would cause the app to crash.
> Post to the message queue when resetting a NavHostFragment

- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavigator.kt
Fixes #219 
Properly pop all modal context destinations off the backstack when navigating back to the default context.
> Allow multiple modal destinations on the backstack

- demo/src/main/res/layout/fragment_image_viewer.xml
- demo/src/main/res/layout/fragment_number_bottom_sheet.xml
- demo/src/main/res/layout/fragment_numbers.xml
- demo/src/main/res/layout/fragment_web_home.xml
- turbo/src/main/res/layout/turbo_fragment_web.xml
- turbo/src/main/res/layout/turbo_fragment_web_bottom_sheet.xml
The hardcoded heights caused toolbar titles or subtitles to be clipped on certain devices or when a non-default font size was selected in the system settings. The heights are now set to `wrap_content`.
> Replace hardcoded toolbar heights in fragment layouts with wrap_content

- turbo/src/main/kotlin/dev/hotwire/turbo/observers/TurboWindowThemeObserver.kt
This avoids an edge-case crash when a `Fragment` is detached from its `Activity` while the system bar color animation is running.
> Fix a potential crash from the Window theme observer

- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboView.kt
This seeks to resolve two crashes that are difficult to reproduce.
This was introduced in #236:
```
java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
at androidx.fragment.app.Fragment.getViewLifecycleOwner(SourceFile:361)
at dev.hotwire.turbo.delegates.TurboWebFragmentDelegate.getViewLifecycleOwner
at dev.hotwire.turbo.delegates.TurboWebFragmentDelegate.visit
at dev.hotwire.turbo.delegates.TurboWebFragmentDelegate.access$visit
at dev.hotwire.turbo.delegates.TurboWebFragmentDelegate$attachWebViewAndVisit$1.invoke
at dev.hotwire.turbo.delegates.TurboWebFragmentDelegate$attachWebViewAndVisit$1.invoke
at dev.hotwire.turbo.delegates.TurboWebFragmentDelegate$attachWebView$2.invoke
at …
```
> Avoid edge-case crashes when attaching the webview to the TurboView

- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavGraphBuilder.kt
Newer versions of the navigation library do not recreate/clear the backstack when updating the nav graph in `NavController.setGraph()` if it's identical to the existing one. This brings back the previous behavior of `TurboSessionNavHostFragment.reset()` by using a random `Int` as a graph `unique_instance` argument.
This also switches to `String`-based routes instead of using an `ID`, since the navigation library has deprecated the `ID`-based approach.
> Fix resetting the `TurboSessionNavHostFragment`

- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboUriHelper.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/util/TurboUriHelperTest.kt
This PR adds checks for a [path traversal attacks](https://developer.android.com/topic/security/risks/path-traversal).
A malicious app can inject URIs of files with file names containing characters such as "../" that when resolved cause the file to be written to parent directories and even rewrite content of existing files.
The changes in this PR prevent this.
> Prevent path traversal vulnerability in TurboUriHelper

- turbo/src/main/assets/json/test-configuration.json
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepositoryTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/nav/TurboNavRuleTest.kt
Don't allow a custom POP presentation (defined in the path configuration) to pop the backstack from the start destination. This will lead to a crash on the next navigation attempt, due to an inconsistent state in the backstack entries and the `TurboNavRule` requirements.
> Prevent a POP presentation from the start destination

- demo/android-lint.xml
- demo/build.gradle
Latest Android gradle plugin introduced a new lint rule which fails for the demo app due to Glide providing a `NotificationTarget`:
```
When targeting Android 13 or higher, posting a permission requires holding the POST_NOTIFICATIONS permission (usage from com.bumptech.glide.request.target.NotificationTarget) [NotificationPermission]
Explanation for issues of type "NotificationPermission":
When targeting Android 13 and higher, posting permissions requires holding
the runtime permission android.permission.POST_NOTIFICATIONS.
```
More information: https://github.com/bumptech/glide/issues/4940
This PR adds a lint config for the demo module which suppresses it as we never post notifications from it.
> Suppress Glide lint error

- turbo/src/main/res/layout/turbo_view.xml
- turbo/src/main/res/layout/turbo_view_bottom_sheet.xml
Fixes #206:
> ... when you have an input field in a bottom modal sheet and you focus on it to type, the viewport for the page behind the modal shrinks a bit ...
It does so by changing the scaleType of the ImageView that holds a screenshot of a detached WebView page to [`matrix`](https://developer.android.com/reference/android/widget/ImageView#setImageMatrix(android.graphics.Matrix)). Not setting any value programmatically leaves the image unchanged even when the height of the ImageView changes (due to the keyboard popping up).
> Prevent web page screenshot scaling down in some cases

- demo/src/main/AndroidManifest.xml
- turbo/build.gradle
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboActivityDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavigator.kt
This allows the library's navigation to respect Android 13/14's new predictive back gesture. Documentation: https://developer.android.com/guide/navigation/predictive-back-gesture
This disable the `Activity`'s `OnBackPressedCallback` when the current nav controller is at its start destination. This allows the system to take control over the back behavior when leaving the app and display a custom animation.
Even if a particular user doesn't not have the "Preditive back animations" Developer Option enabled in Android 13, this change still provides a tangible benefit. The app's main Activity will no longer `.finish()` when using the back gesture/button to leave the app. For the first time, Android 13 maintains the `Activity` instance if an app does not manually call `.finish()`.
On Android …
> Support Android 13's predictive back gesture

- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboExtensions.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/visit/TurboVisitResponse.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/visit/TurboVisitResponseTest.kt
Addresses https://github.com/hotwired/turbo-android/pull/264 by truncating the middle of the html response so it's still clear what type of response was received and adding the response length.
The log output now looks like:
```
TurboVisitResponse(statusCode=200, responseHTML=<!DOCTYPE html><html lang [...] r> </main> </body></html>, responseLength=3036)
```
> Improve how a TurboVisitResponse is logged

- demo/src/debug/AndroidManifest.xml
Hi. I'm trying to learn how turbo-android should work, so I cloned this repo and the [turbo-native-demo](https://github.com/hotwired/turbo-native-demo) repo. I was able to start the android app on an emulator and it loaded the content from the official site. Perfect :)
Then I made this change to hook it up with my local clone of `turbo-native-demo`:
```diff
diff --git a/demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Constants.kt b/demo/src/main/kotlin/dev/hotwire/turbo/
demo/util/Constants.kt
index 1be473e..dfdabb3 100644
--- a/demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Constants.kt
+++ b/demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Constants.kt
@@ -1,6 +1,6 @@
package dev.hotwire.turbo.demo.util
-const val BASE_URL = "https://turbo-native-demo.glitch.me"
+const val BASE_URL = …
```
> Allow clear text traffic in debug build

- build.gradle
- turbo/build.gradle
- turbo/proguard-consumer-rules.pro
- turbo/proguard-rules.pro
This fixes release build issues after upgrading to AGP `8.x`:
```
> Task :turbo:minifyProfilingWithR8 FAILED
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /Users/johms/Work/hotwired/turbo-android/turbo/build/outputs/mapping/profiling/missing_rules.txt.
ERROR: R8: Missing class java.lang.invoke.StringConcatFactory (referenced from: java.lang.String dev.hotwire.turbo.config.TurboPathConfiguration$Location.toString() and 27 other contexts)
```
> Fix R8 build issues

- demo/src/main/kotlin/dev/hotwire/turbo/demo/main/MainActivity.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/main/MainSessionNavHostFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Extensions.kt
- docs/ADVANCED-OPTIONS.md
- turbo/src/main/kotlin/dev/hotwire/turbo/config/Turbo.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboConfig.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRule.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboCameraCaptureDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboFileChooserDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/http/TurboHttpClient.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/http/TurboHttpRepository.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboLog.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboUriHelper.kt
Previously, you needed a `TurboSession` instance to enable/disable debug logging. However, this was deceiving, since that debug setting was global across all sessions. The change in this PR reflects that debug logging is global across the app and can be set anywhere (ideally once).
**Before:**
```kotlin
class MainSessionNavHostFragment : TurboSessionNavHostFragment() {
// ...
override open fun onSessionCreated() {
super.onSessionCreated()
if (BuildConfig.DEBUG) {
session.setDebugLoggingEnabled(true)
}
}
```
**Now:**
```kotlin
if (BuildConfig.DEBUG) {
Turbo.config.debugLoggingEnabled = true
}
```
Additionally, logged errors now include the exception stacktrace.
> Improve how debug logging is enabled and how exceptions are logged

- demo/build.gradle
- demo/src/main/assets/json/configuration.json
- demo/src/main/kotlin/dev/hotwire/turbo/demo/base/NavDestination.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/main/MainActivity.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/main/MainSessionNavHostFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/strada/BridgeComponentFactories.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/strada/FormComponent.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/strada/MenuComponent.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/strada/MenuComponentAdapter.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/strada/OverflowMenuComponent.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Extensions.kt
- demo/src/main/res/drawable/ic_overflow.xml
- demo/src/main/res/layout/form_component_submit.xml
- demo/src/main/res/layout/menu_component_adapter_row.xml
- demo/src/main/res/layout/menu_component_bottom_sheet.xml
- demo/src/main/res/menu/web.xml
This add 3 Strada sample components to the Demo app:
- `FormComponent`: displays a submit button in the native toolbar, which will submit the form on the page when tapped.
- `MenuComponent`: displays a native bottom sheet menu, which will send the selected index of the tapped menu item back to the web.
- `OverflowMenuComponent`: displays a native 3-dot menu in the toolbar, which will will notify the web when it has been tapped.
> Strada sample components in the Demo app

- build.gradle
- demo/build.gradle
- turbo/build.gradle
This PR:
- Updates the compile/target SDK to 34
- Upgrades the build tools to be compatible with SDK 34
- Bumps many `androidx.*` dependencies, which have some new features available
> Upgrade to SDK 34 and bump dependencies to latest versions

- turbo/src/main/assets/js/turbo_bridge.js
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/session/TurboSessionTest.kt
Currently, when Turbo submits a form and redirects back to the same page, the current destination fragment is recreated. This displays a visual flash and doesn't work well with the upcoming Turbo 8 morphing feature.
To fix this, visit proposals for the same page are no longer proposed to the app. Instead, an immediate Turbo visit is started in the WebView so Turbo can seamlessly handle the visit and provide a better visual update with morphing.
> Perform same-page visit proposals without recreating the current destination

- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
`replace_root` presentation may not remove all previous navigation items in the back stack.
Inclusive `popUpTo` pops every navigation items until it finds the given one, leaving previous navigation items stacked before it, depending of the previous navigation flow.
Popping up to the graph id ensures the back stack is fully cleared.
> REPLACE_ROOT presentation - popUpTo to controller.graph.id (inclusive)

- turbo/src/main/assets/json/test-configuration.json
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepositoryTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationTest.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/nav/TurboNavRuleTest.kt
> Anim replace root

- turbo/src/main/assets/json/test-configuration.json
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavRule.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/nav/TurboNavRuleTest.kt
Not sure if this is Kotlin-way of doing. Also not sure about tests.
> Allow animation customization for replace_root presentation (fixes #285)

- docs/PATH-CONFIGURATION.md
Fixes https://github.com/hotwired/turbo-android/issues/203
@jayohms curious if there's anything else special you do at Basecamp regarding path config? I just documented how I have done it in the past since I agree it'd be helpful to be clear about this.
> Expand docs on remote path configuration

- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavigator.kt
To properly handle dismissing bottom sheet dialog fragments, it's necessary to cancel the `dialog` instance instead of popping the backstack to receive all the desired `Fragment` callbacks. Previously, calling `navigateBack()` or `navigateUp()` would dismiss the bottom sheet, but leave the underlying `WebView` screen stuck on a screenshot instead of the interactive attached `WebView`.
Fixes https://github.com/hotwired/turbo-android/issues/197
> Properly handle navigate back/up from bottom sheet dialog fragments

- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavigator.kt
Ensure that `clearBackStack()` works correctly when called from a bottom sheet fragment. Follow up to https://github.com/hotwired/turbo-android/pull/306
Fixes https://github.com/hotwired/turbo-android/issues/260
> Fix `clearBackStack()` from a bottom sheet dialog fragment

- turbo/src/main/res/layout/turbo_view.xml
Fixes https://github.com/hotwired/turbo-android/issues/230
> Allows error views to be scrolled without pull-to-refresh interference

- turbo/src/main/assets/js/turbo_bridge.js
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboSwipeRefreshLayout.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboWebView.kt
This fixes: https://github.com/hotwired/turbo-android/issues/294
This prevents pull-to-refresh from being triggered when (potentially) nested scrolling within an element on the page that is using `overflow-y: scroll` or `overflow-y: auto`. To address this, the following item were added:
- On every touch start, check if the target element or any of its parent elements are scrollable. If any are scrollable, notify the `TurboWebView` that the currently touched element is scrollable.
- On every touch end, reset the internal state of the `TurboWebView`.
- Whenever the `TurboSwipeRefreshLayout` checks to see if its scrollable child can scroll up, check the state of the `TurboWebView` if a scrollable element is currently being touched.
> Prevent pull-to-refresh from triggering while scrolling in a nested scrollable element on the page

- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/imageviewer/ImageViewerFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebModalFragment.kt
- demo/src/main/kotlin/dev/hotwire/turbo/demo/util/Extensions.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavDestination.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/nav/TurboNavigator.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/util/TurboExtensions.kt
- turbo/src/main/res/drawable/ic_back.xml
- turbo/src/main/res/drawable/ic_close.xml
Fixes https://github.com/hotwired/turbo-android/issues/188
It's no longer necessary to have a unique start destination `Fragment` instance from other destinations for the `Toolbar` back button to properly display.
> Fix `Toolbar` back button visibility without having a separate start destination `Fragment` instance

- demo/src/main/kotlin/dev/hotwire/turbo/demo/main/MainSessionNavHostFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSessionNavHostFragment.kt
Addresses https://github.com/hotwired/turbo-android/issues/194
> Add missing TurboSessionNavHostFragment API documentation

- README.md
- docs/INSTALLATION.md
- docs/QUICK-START.md
Update the readme documentation to give `build.gradle.kts` examples, since that's now the Android default. 
Follow up to #302
> Readme documentation improvements

- docs/INSTALLATION.md
- docs/QUICK-START.md
This PR updates the Installation guide to use the correct syntax and reference the current build.gradle file
which is renamed to build.gradle.kts in new android apps.
I removed this section of code because it is already settings.gradle.kts file
`repositories {
mavenCentral()
}`
> Updating the Installation and Quickstart documentation to use build.gradle.kts

- turbo/src/main/kotlin/dev/hotwire/turbo/errors/HttpError.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/errors/HttpErrorTest.kt
Add missing 402 status code error handling. I'm using this status code to render native in-app purchase modals.
> Add 402: Payment Required

- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
This change prevents displaying an error view and resetting the session when a 3rd party resource is requested on a page with an SSL error. Error views should only be displayed when the main visit url fails to load from an SSL error.
> Only show error screens for SSL errors when the url matches the current visit

- demo/src/main/kotlin/dev/hotwire/turbo/demo/features/web/WebBottomSheetFragment.kt
This is being done for completeness' sake. I used the demo as a source of truth for my Strada integration, but I needed to add a button to the menu in a bottom sheet. This did not work and had me scratching my head, wondering why it was not working, yet Strada was wired up correctly. Then I realized that `WebBottomSheetFragment` did not extend `WebFragment` so all the `BridgeDelegate` stuff was not set up in the bottom sheet. This adds this setup to the `WebBottomSheetFragment` in the demo so that others do not run into this issue as I did.
Could we abstract this away so it's not duplicated? Yeah, but I'm calling YAGNI at this point as it's a demo.
> Add Strada integration to WebBottomSheetFragment in demo

- turbo/src/main/assets/js/turbo_bridge.js
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSessionCallback.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/session/TurboSessionTest.kt
The core `turbo.js` library does not permit cross-origin visit requests (i.e. a link that redirects to an external domain). These requests call the adapter method `visitRequestFailedWithStatusCode(visit, statusCode)` for all platforms. 
To handle this in the [browser adapter](https://github.com/hotwired/turbo/blob/main/src/core/native/browser_adapter.js#L41-L55), non-HTTP status code failures update the `window.location` so the browser can handle the top-level redirect. The browser adapter does not actually know whether a cross-origin redirect was attempted, since the CORS policy restricts requests to the `same-origin`, but updating the `window.location` directly bypasses needing this knowledge.
The mobile adapters, however, can't just update the `window.location` — a new visit needs to …
> Detect cross-origin visit request attempts

- turbo/src/main/kotlin/dev/hotwire/turbo/http/TurboHttpClient.kt
Ensure the `loggingInterceptor` is declared before any public functions can be called into the singleton instance.
> Fix potential crash from HTTP logging interceptor

- turbo/build.gradle.kts
Resolves: https://github.com/hotwired/turbo-android/issues/328
Addresses security vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2023-3635
> Bump OkHttp to 4.12.0

- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationLoader.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepository.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/config/TurboPathConfigurationRepositoryTest.kt
- turbo/src/test/resources/http-responses/test-configuration-malformed.json
When the Turbo Path Configuration file is malformed or in a wrong format, parsing it from JSON can result in an exception being thrown. This PR adds checks and error handling for such cases.
> Path Configuration parsing fix

- turbo/src/main/assets/js/turbo_bridge.js
- turbo/src/main/kotlin/dev/hotwire/turbo/delegates/TurboWebFragmentDelegate.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebBottomSheetDialogFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/fragments/TurboWebFragment.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/session/TurboSession.kt
- turbo/src/main/kotlin/dev/hotwire/turbo/views/TurboWebView.kt
- turbo/src/test/kotlin/dev/hotwire/turbo/session/TurboSessionTest.kt
This backports the functionality in https://github.com/hotwired/hotwire-native-android/pull/160. See the Hotwire Native PR for details.
> Backport the ability to fix same page restores from `hotwire-native-android`
